export const FETCH_LAST_GAME_DATE_START = 'ranking/FETCH_LAST_GAME_DATE_START';
export const FETCH_LAST_GAME_DATE_SUCCESS = 'ranking/FETCH_LAST_GAME_DATE_SUCCESS';
export const FETCH_LAST_GAME_DATE_FAIL = 'ranking/FETCH_LAST_GAME_DATE_FAIL';

export const FETCH_RANKING_START = 'ranking/FETCH_RANKING_START';
export const FETCH_RANKING_SUCCESS = 'ranking/FETCH_RANKING_SUCCESS';
export const FETCH_RANKING_FAIL = 'ranking/FETCH_RANKING_FAIL';
